### ISSUE TITLE
remapping keys for `PgUp` and `PgDn`

### ISSUE THREAD

**Issue by englut** [RasmusLindroth/tut#279]
Hi there, I'm finding I'm having a hard time breaking my habits with vim for `PgUp` and `PgDn`. I use `Ctrl-J` and `Ctrl-K`, respectively. I was wondering if we can get two more options for remapping the keys of `PgUp` and `PgDn`. 🙏

Would be cool to be able to configure it like this:
```toml
[input.global-pgup]
special-keys=["PgUp"]

[input.global-pgdn]
special-keys=["PgDn"]
```
